generic_txt = 'A plain room.'
exits_txt = '\n\nExits to the '

room_data = {
    '0000':{'current_state': 0,
            'states':{0:{'img':'images/the-well.png',
                         'txt':'Enter your name:'},
                      1:{'img':'images/the-well.png',
                         'txt':'Make your wish:'},
                      2:{'img':'images/the-well.png',
                         'txt':'As you whisper your wish and cast the coin into the well, it rumbles. Light bursts out from deep below, and you tumble into the well!'}},
            'exits':{'N':'ENTR'}},
    'DEAD':{'current_state': 0,
            'states':{0:{'img':'images/game-over.png',
                         'txt':'The well claims another...'}},
            'exits':{'N':'ENTR'}},
    'WIN!':{'current_state': 0,
            'states':{0:{'img':'images/the-well.png',
                         'txt':'You escaped! Fresh air fills your lungs and joy fills your heart!'},
                      1:{'img':'images/the-well.png',
                         'txt':'===DISPLAY WISH AND SCORE==='}},
            'exits':{'N':'ENTR'}},
    'ENTR':{'current_state': 0,
            'states':{0:{'img':'images/entrance.png',
                         'txt':f'You stand in a stone room, the well shaft high above, tantalizingly out of reach.{exits_txt}North, East, South, and West'},
                      1:{'img':'images/entrance.png',
                         'txt':f'The well room. If only you could find something to climb back up with...{exits_txt}North, East, South, and West'},
                      2:{'img':'images/entrance.png',
                         'txt':f'The well room! You can escape with the grappeling hook!'},
                      3:{'img':'images/entrance.png',
                         'txt':f'You decide to keep exploring...{exits_txt}North, East, South, and West'}},
            'exits':{'N':'1Nxx', 'E':'1Exx', 'S':'1Sxx', 'W':'HP#1'}},
    '1Nxx':{'current_state': 0,
            'states':{0:{'img':'images/two-exits.png',
                         'txt': f'{generic_txt}{exits_txt}North and South'}},
            'exits':{'N':'LM_N', 'S':'ENTR'}},
    '1Exx':{'current_state': 0,
            'states':{0:{'img':'images/two-exits.png',
                         'txt':f'{generic_txt}{exits_txt}East, and West'}},
            'exits':{'E':'LM_E', 'W':'ENTR'}},
    '1Sxx':{'current_state': 0,
            'states':{0:{'img':'images/two-exits.png',
                         'txt': f'{generic_txt}{exits_txt}North and South'}},
            'exits':{'N':'ENTR', 'S':'2Sxx'}},
    '2Sxx':{'current_state': 0,
            'states':{0:{'img':'images/two-exits.png',
                         'txt': f'{generic_txt}{exits_txt}North and West'}},
            'exits':{'N':'1Sxx', 'W':'LM_S'}},
    '2S2W':{'current_state': 0,
            'states':{0:{'img':'images/two-exits.png',
                         'txt': f'{generic_txt}{exits_txt}North and East'}},
            'exits':{'N':'LMSW', 'E':'LM_S'}},
    '1S3W':{'current_state': 0,
            'states':{0:{'img':'images/two-exits.png',
                         'txt': f'{generic_txt}{exits_txt}North and East'}},
            'exits':{'N':'LM_W', 'E':'LMSW'}},
    '4Wxx':{'current_state': 0,
            'states':{0:{'img':'images/two-exits.png',
                         'txt': f'{generic_txt}{exits_txt}East and West'}},
            'exits':{'W':'BTLW', 'E':'LM_W'}},
    '1N3W':{'current_state': 0,
            'states':{0:{'img':'images/two-exits.png',
                         'txt': f'{generic_txt}{exits_txt}South and East'}},
            'exits':{'S':'LM_W', 'E':'1N2W'}},
    '1N2W':{'current_state': 0,
            'states':{0:{'img':'images/two-exits.png',
                         'txt': f'{generic_txt}{exits_txt}North and West'}},
            'exits':{'N':'LMNW', 'W':'1N3W'}},
    '2N1W':{'current_state': 0,
            'states':{0:{'img':'images/two-exits.png',
                         'txt': f'{generic_txt}{exits_txt}East and West'}},
            'exits':{'E':'LM_N', 'W':'LMNW'}},
    '2N1E':{'current_state': 0,
            'states':{0:{'img':'images/two-exits.png',
                         'txt': f'{generic_txt}{exits_txt}East and West'}},
            'exits':{'E':'LMNE', 'W':'LM_N'}},
    '2N3E':{'current_state': 0,
            'states':{0:{'img':'images/two-exits.png',
                         'txt': f'{generic_txt}{exits_txt}East and West'}},
            'exits':{'E':'2N4E', 'W':'LMNE'}},
    '2N4E':{'current_state': 0,
            'states':{0:{'img':'images/two-exits.png',
                         'txt': f'{generic_txt}{exits_txt}East and West'}},
            'exits':{'E':'BTLE', 'W':'2N3E'}},
    '1N5E':{'current_state': 0,
            'states':{0:{'img':'images/two-exits.png',
                         'txt': f'{generic_txt}{exits_txt}North and South'}},
            'exits':{'N':'BTLE', 'S':'5Exx'}},
    '5Exx':{'current_state': 0,
            'states':{0:{'img':'images/two-exits.png',
                         'txt': f'{generic_txt}{exits_txt}North and South'}},
            'exits':{'N':'1N5E', 'S':'1S5E'}},
    '1S5E':{'current_state': 0,
            'states':{0:{'img':'images/three-exits.png',
                         'txt': f'{generic_txt}{exits_txt}North, East, and West'}},
            'exits':{'N':'5Exx', 'E':'4TRP','W':'LMSE'}},
    '1S3E':{'current_state': 0,
            'states':{0:{'img':'images/three-exits.png',
                         'txt': f'{generic_txt}{exits_txt}South, East, and West'}},
            'exits':{'S':'LW_E', 'E':'LMSE', 'W':'1S2E'}},
    '1S2E':{'current_state': 0,
            'states':{0:{'img':'images/two-exits.png',
                         'txt': f'{generic_txt}{exits_txt}North and East'}},
            'exits':{'N':'LM_E', 'E':'1S3E'}},
    '1N2E':{'current_state': 0,
            'states':{0:{'img':'images/two-exits.png',
                         'txt': f'{generic_txt}{exits_txt}North and South'}},
            'exits':{'N':'LMNE', 'S':'LM_E'}},
    'LM_N':{'current_state': 0,
            'states':{0:{'img':'images/decisions.png',
                         'txt': f'You come across a statue of a women holding a coin in her right hand, and a key in her left.{exits_txt}East and West'},
                      1:{'img':'images/decisions.png',
                         'txt': f'The room with the statue holding a coin and a key. What could it mean?{exits_txt}East, South, and West'}},
            'exits':{'E':'2N1E', 'S':'1Nxx', 'W':'2N1W'}},
    'LMNE':{'current_state': 0,
            'states':{0:{'img':'images/cacti.png',
                         'txt': f'You come across a room full of... Cacti? How odd...{exits_txt}North, East, South, and West'},
                      1:{'img':'images/cacti.png',
                         'txt': f'The cactus room. How do they grow without sunlight?{exits_txt}North, East, South, and West'},
                      2:{'img':'images/cacti.png',
                         'txt': f'The cactus room. Cruel joke.{exits_txt}North, East, South, and West'}},
            'exits':{'N':'^TRP', 'E':'2N3E', 'S':'1N2E', 'W':'2N1E'}},
    'LM_E':{'current_state': 0,
            'states':{0:{'img':'images/clock.png',
                         'txt': f"You come across a room with an arcane clock. You feel a strong urge to speed up. Is it natural, or is the clock messing with you magically?{exits_txt}North, South, and West"},
                      1:{'img':'images/clock.png',
                         'txt': f"The room with the arcane clock. You probably don't have much time...{exits_txt}North, South, and West"}},
            'exits':{'N':'1N2E', 'S':'1S2E', 'W':'1Exx'}},
    'LMSE':{'current_state': 0,
            'states':{0:{'img':'images/music.png',
                         'txt': f'You come across a room with music notes painted on the walls. To bad this game is silent...{exits_txt}East and West'},
                      1:{'img':'images/music.png',
                         'txt': f'The room with the music notes. {exits_txt}East and West'},
                      2:{'img':'images/music.png',
                         'txt': f"The room with the music notes. That otherworldly tune is such an earworm, it will never give you up...{exits_txt}East and West"}},
            'exits':{'E':'1S5E', 'W':'1S3E'}},
    'LM_S':{'current_state': 0,
            'states':{0:{'img':'images/red-herring.png',
                         'txt': f'You come across a room with... a giant red fish painted on the floor?! What?!{exits_txt}East, South, and West'},
                      1:{'img':'images/red-herring.png',
                         'txt': f"The room with the fish painting. Some things just don't make sense.{exits_txt}East, South, and West"},
                      2:{'img':'images/red-herring.png',
                         'txt': f'The room with the red herring. If only you had caught on sooner...{exits_txt}East, South, and West'}},
            'exits':{'E':'2Sxx', 'S':'$TRP', 'W':'2S2W'}},
    'LMSW':{'current_state': 0,
            'states':{0:{'img':'images/graffiti.png',
                         'txt': f'You come across a room covered in arcane symbols... or is that graffiti?{exits_txt}South, and West'},
                      1:{'img':'images/graffiti.png',
                         'txt': f'The room with the magic graffiti. Who knows what it means?{exits_txt}South, and West'}},
            'exits':{'S':'2S2W', 'W':'1S3W'}},
    'LM_W':{'current_state': 0,
            'states':{0:{'img':'images/shooting-star.png',
                         'txt': f"You come across a mural of a shooting-star. You'd make a wish, but last time didn't turn out so good...{exits_txt}North, East, South, and West"},
                      1:{'img':'images/shooting-star.png',
                         'txt': f'The shooting-star room. That star would look good on a red sweater.{exits_txt}North, South, and West'}},
            'exits':{'N':'1N3W', 'S':'1S3W', 'W':'4Wxx'}},
    'LMNW':{'current_state': 0,
            'states':{0:{'img':'images/sword-statue.png',
                         'txt': f'You come across a statue of a warrior. You notice he has a scabbard but no sword.{exits_txt}North, East, and South'},
                      1:{'img':'images/sword-statue.png',
                         'txt': f'The room with the swordless statue. Wonder if he left it somewhere?{exits_txt}North, East, and South'},
                      2:{'img':'images/sword-statue.png',
                         'txt': f"The room with the swordless statue. Too bad he can't use the one you found.{exits_txt}North, East, and South"},
                      3:{'img':'images/sword-statue.png',
                         'txt': f"The room with the swordless statue. Sorry bro, this one's mine!{exits_txt}North, East, and South"}},
            'exits':{'N':'SWRD', 'E':'2N1W', 'S':'1N2W'}},
    'HP#1':{'current_state': 0,
            'states':{0:{'img':'images/potion.png',
                         'txt': f"You find a health potion! That'll be useful."},
                      1:{'img':'images/empty-pedestal.png',
                         'txt': f'The room where you found a health potion.'}},
            'exits':{'E':'ENTR'}},
    'HP#2':{'current_state': 0,
            'states':{0:{'img':'images/potion.png',
                         'txt': f"You find a health potion! That'll be useful."},
                      1:{'img':'images/empty-pedestal.png',
                         'txt': f'The room where you found a health potion.'}},
            'exits':{'S':'BTLE'}},
    'HP#3':{'current_state': 0,
            'states':{0:{'img':'images/potion.png',
                         'txt': f"You find a health potion! That'll be useful."},
                      1:{'img':'images/empty-pedestal.png',
                         'txt': f'The room where you found a health potion.'}},
            'exits':{'N':'BTLW'}},
    'SWRD':{'current_state': 0,
            'states':{0:{'img':'images/sword.png',
                         'txt': f"You find a sword! That'll be useful."},
                      1:{'img':'images/empty-pedestal.png',
                         'txt': f'The room where you found your sword.'}},
            'exits':{'S':'LMNW'}},
    'LW_E':{'current_state': 0,
            'states':{0:{'img':'images/lost-wish.png',
                         'txt': f"You find... a wish? {'\n"I wish my little one would heal quickly..."\n'} Sadly it's not yours, but maybe it'll prove useful."},
                      1:{'img':'images/empty-pedestal.png',
                         'txt': f'The room where you found a lost wish.'}},
            'exits':{'N':'1S3E'}},
    'LW_W':{'current_state': 0,
            'states':{0:{'img':'images/lost-wish.png',
                         'txt': f"You find... a wish? {'\n"I wish for the power to protect my homeland..."\n'} Sadly it's not yours, but maybe it'll prove useful."},
                      1:{'img':'images/empty-pedestal.png',
                         'txt': f'The room where you found a lost wish.'}},
            'exits':{'S':'BTLW'}},
    '4TRP':{'current_state': 0,
            'states':{0:{'img':'images/fourth-wall-trap.png',
                         'txt': f"A dead end with nothing on the second or third walls, but you notice that the fourth has a large crack in it..."},
                      1:{'img':'images/dead-end.png',
                         'txt': f'Just a normal dead-end with four very sturdy, unbreakable walls. Nothing to see here folks!'}},
            'exits':{'E':'1S5E'}},
    '^TRP':{'current_state': 0,
            'states':{0:{'img':'images/spike-trap.png',
                         'txt': f"Ack! Spike pit!"},
                      1:{'img':'images/spike-trap.png',
                         'txt': f"At least you're alive..."},
                      2:{'img':'you died', 'txt':'none of this will be displayed'}},
            'exits':{'S':'LMNE'}},
    '$TRP':{'current_state': 0,
            'states':{0:{'img':'images/stairway-trap.png',
                         'txt': f"Stairs! You can escape!"},
                      1:{'img':'images/climbing-stairs.png',
                         'txt': f'You begin the climb. It looks like its a long way up...'},
                      2:{'img':'images/climbing-stairs.png',
                         'txt': f'You keep climbing, still no end in sight'},
                      3:{'img':'images/climbing-stairs.png',
                         'txt': f'You keep climbing, but something feels... off'},
                      4:{'img':'images/stairway-trap.png',
                         'txt': f"You round the corner, and... you're at the bottom? That was way less steps than it took you to go up. This feels like a trick..."},
                      5:{'img':'images/stairway-trap.png',
                         'txt': f'Infinite stairs might be good for leg day, but you need to find a real way out of here...'}},
            'exits':{'N':'LM_S'}},
    'WISH':{'current_state': 0,
            'states':{0:{'img':'images/wish.png',
                         'txt': f"You find your wish!"},
                      1:{'img':'images/empty-pedestal.png',
                         'txt': f'The room where you found your wish.'}},
            'exits':{'E':'BTLW'}},
    'EXIT':{'current_state': 0,
            'states':{0:{'img':'images/escape-hook.png',
                         'txt': f"You find a grappeling hook! Maybe you can use it to escape!"},
                      1:{'img':'images/empty-pedestal.png',
                         'txt': f'The room where you found the grappeling hook.'}},
            'exits':{'E':'BTLE'}},
    'BTLE':{'current_state': 0,
            'states':{0:{'img':'images/ghost-battle.png',
                         'txt':f'BOO! A ghost is in this room!'},
                      1:{'img':'images/ghost-battle.png',
                         'txt':f'"Little one!" the ghost screeches. Is it mocking you?!\nWhat do you do?'},
                      2:{'img':'images/ghost-battle.png',
                         'txt':f'You manage to escape! Where do you flee to? {exits_txt}North, East, South, and West'},
                      3:{'img':'images/ghost-battle.png',
                         'txt':f'The Ghost rears up to attack!\nWhat do you do?'},
                      4:{'img':'images/ghost-battle.png',
                         'txt':f'The Ghost enters a defensive position!\nWhat do you do?'},
                      5:{'img':'images/ghost-battle.png',
                         'txt':f'===ATK_RESULTS==='},
                      6:{'img':'images/ghost-peace.png',
                         'txt':f'The ghost has been pacified.{exits_txt}North, East, South, and West'},
                      7:{'img':'images/ghost-peace.png',
                         'txt':f'===PEACE_RESULTS==='},
                      8:{'img':'images/four-exits.png',
                         'txt':f'A large (now ghost free) room.{exits_txt}North, East, South, and West'},
                      9:{'img':'images/ghost-battle.png',
                         'txt':'===OFFER_WISH==='}},
            'exits':{'N':'HP#2', 'E':'EXIT', 'S':'1N5E', 'W':'2N4E'}},
    'BTLW':{'current_state': 0,
            'states':{0:{'img':'images/ghost-battle.png',
                         'txt':f'BOO! A ghost is in this room!'},
                      1:{'img':'images/ghost-battle.png',
                         'txt':f'"POWER!" the ghost screeches. Terrifing!\nWhat do you do?'},
                      2:{'img':'images/ghost-battle.png',
                         'txt':f'You manage to escape! Where do you flee to? {exits_txt}North, East, South, and West'},
                      3:{'img':'images/ghost-battle.png',
                         'txt':f'The Ghost rears up to attack!\nWhat do you do?'},
                      4:{'img':'images/ghost-battle.png',
                         'txt':f'The Ghost enters a defensive position!\nWhat do you do?'},
                      5:{'img':'images/ghost-battle.png',
                         'txt':f'===ATK_RESULTS==='},
                      6:{'img':'images/ghost-peace.png',
                         'txt':f'The ghost has been pacified.{exits_txt}North, East, South, and West'},
                      7:{'img':'images/ghost-peace.png',
                         'txt':f'===PEACE_RESULTS==='},
                      8:{'img':'images/four-exits.png',
                         'txt':f'A large (now ghost free) room.{exits_txt}North, East, South, and West'},
                      9:{'img':'images/ghost-battle.png',
                         'txt':'===OFFER_WISH==='}},
            'exits':{'N':'LW_W', 'E':'4Wxx', 'S':'HP#3', 'W':'WISH'}}    
}

'''
the long way to get room text:
room_data['ENTR']['states'][room_data['ENTR']['current_state']]['txt']

instead, you should break it up into reusable variables:
room = room_data['ENTR']
cs = room['current_state']
etc.
'''